name: Test

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        description: runner
        options: 
        - test

      multiple:
        type: boolean
        default: false
      sleep:
        type: number
        default: 1

jobs:
  test:
    strategy:
      matrix:
        n: ${{ github.event.inputs.multiple == 'false' && fromJSON('[0]') || fromJSON('[0, 1, 2]') }}
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Sleep
        run: sleep ${{ github.event.inputs.sleep }}
      - name: Run a one-line script
        run: echo "Hello, World! - ${{ matrix.n }}"
      - name: Test Command
        run: "jq --help || :"

