name: Test

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
      multiple:
        type: boolean
        default: false

jobs:
  test:
    strategy:
      matrix:
        n: ${{ github.event.inputs.multiple == 'false' && fromJSON('[0]') || fromJSON('[0, 1, 2]') }}
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Run a one-line script
        run: echo "Hello, World! - ${{ matrix.n }}"
